export const COMPLETE_CONFIGURE_STEP = 'COMPLETE_CONFIGURE_STEP';
export const COMPLETE_RECIPIENTS_STEP = 'COMPLETE_RECIPIENTS_STEP';
export const COMPLETE_REVIEW_STEP = 'COMPLETE_REVIEW_STEP';
export const DISCARD_BROADCAST = 'DISCARD_BROADCAST';
